<?php

namespace App\Models;

use App\Models\Concerns\HasOrganizationScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Enterprise Health Score
 *
 * Daily snapshot of organizational health across 8 domains.
 * Generated by the Enterprise Brain's Operational Intelligence Core.
 */
class EnterpriseHealthScore extends Model
{
    use HasFactory, HasOrganizationScope;

    protected $fillable = [
        'organization_id', 'scored_at',
        'revenue_health', 'customer_health', 'security_health', 'agent_health',
        'workflow_health', 'compliance_health', 'operational_health', 'technology_health',
        'enterprise_health_score', 'domain_details', 'alerts', 'recommendations',
    ];

    protected $casts = [
        'scored_at' => 'date',
        'revenue_health' => 'decimal:2',
        'customer_health' => 'decimal:2',
        'security_health' => 'decimal:2',
        'agent_health' => 'decimal:2',
        'workflow_health' => 'decimal:2',
        'compliance_health' => 'decimal:2',
        'operational_health' => 'decimal:2',
        'technology_health' => 'decimal:2',
        'enterprise_health_score' => 'decimal:2',
        'domain_details' => 'array',
        'alerts' => 'array',
        'recommendations' => 'array',
    ];

    public function organization(): BelongsTo
    {
        return $this->belongsTo(Organization::class);
    }
}
